TST - .....

diff --git a/.github/workflows/security-reporter-agent.yml b/.github/workflows/security-reporter-agent.yml
--- a/.github/workflows/security-reporter-agent.yml
+++ b/.github/workflows/security-reporter-agent.yml
@@ -25,18 +25,18 @@ jobs:
       - name: Install GitHub Copilot CLI
         run: npm i -g @github/copilot
 
-      - name: Check Copilot token
-        run: |
-          if [ -z "$COPILOT_GITHUB_TOKEN" ]; then
-            echo "❌ Token is missing"
-            exit 1
-          else
-            echo "✅ Token is present"
-          fi
+      # - name: Check Copilot token
+      #   run: |
+      #     if [ -z "$COPILOT_GITHUB_TOKEN" ]; then
+      #       echo "❌ Token is missing"
+      #       exit 1
+      #     else
+      #       echo "✅ Token is present"
+      #     fi
 
       - name: Run Security Agent via Copilot CLI
         env:
-          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REPOSITORY: ${{ github.repository }}
         run: |
           set -euo pipefail
